### ISSUE TITLE
Candidate strings extend beyond frame

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#234]
Another minor regression in #222, the candidate string width isn't correctly calculated; note here how the string extends beyond the right edge.

![image](https://user-images.githubusercontent.com/1134/129954091-86fd3bf0-e15b-4064-9ebb-9b251ce0905a.png)

cc @aikrahguzar

**Comment by aikrahguzar** [comment]
> Another minor regression in #222, the candidate string width isn't correctly calculated; note here how the string extends beyond the right edge.
> 
> ![image](https://user-images.githubusercontent.com/1134/129954091-86fd3bf0-e15b-4064-9ebb-9b251ce0905a.png)
> 

I think this is due to the `invisible` string part. You can try changing the widths in template and the columns will adjust but those fringes will be there because of the invisible part. If you don't want them we have to add the width of invisible part to the calculation  Which means empty space at the end. I prefer fringes to that but it is easy to change.

**Comment by aikrahguzar** [comment]
Though I guess we can reduce `start-width` by 1 so that the fringe indicator doesn't overlap the last character

**Comment by bdarcus** [comment]
> I think this is due to the `invisible` string part.

I don't believe so; 'invisible` means, well, just that: not displayed.

> Though I guess we can reduce start-width by 1 so that the fringe indicator doesn't overlap the last character.

Yes, that seems a good approach.

**Comment by aikrahguzar** [comment]
Sent a pr!
