### ISSUE TITLE
Refactor templates, remove map variable

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#237]
Per suggestion [below](https://github.com/bdarcus/bibtex-actions/issues/237#issuecomment-901846642), let's make templates a little more flexible, so we can simplify elsewhere.

------------

I accidentally left in a second field `mapping` table, which was an experiment in a template approach that would be more CSL field focused.

The advantage of that is you have a generic field name like `container-title`, which then maps to type-specific fields like `booktitle`.

Would make it easier to remove type-specific templates.

Also, I guess I should make that a `defcustom`?

Thoughts?

cc @aikrahguzar

**Comment by aikrahguzar** [comment]
> I accidentally left in a second field `mapping` table, which was an experiment in a template approach that would be more CSL field focused.
> 
> The advantage of that is you have a generic field name like `container-title`, which then maps to type-specific fields like `booktitle`.
> 
> Would make it easier to remove type-specific templates.
> 
> Also, I guess I should make that a `defcustom`?
> 
> Thoughts?

I would go in the other direction and instead use template to determine this kind of mapping. I think as it is we have too many knobs for basically doing the same stuff. I think instead we should use a template of the form
```elisp 
"${author editor:36}    ${date year issued:4}   ${title:60}"
```
i.e the mapping is part of the template and can be adjusted there. I am assuming the field names don't have space in them. If they do we can use another separator like comma. We try each of the alternatives in turn and use the first one that succeeds. This wouldn't be hard to implement and simplify a bunch of details  by putting everything in one place. I think this is true even for the user. If they need an alternate just add it to the proper place in the format string.

This will also get rid of annoying but unlikely in practice scenarios like what happens if the template has both author and editor. They can both be present and with the current default if this happens and author is not present but the editor is we will be displaying the editor names in both columns.

**Comment by bdarcus** [comment]
That makes sense in general.

But how would it interact with `bibtex-actions-get-value`? I'm particularly thinking of crucial fields like `=key=`/`id`.

That function would just look in the template, rather than the variable, maybe with some specific logic for the special fields?

**Comment by bdarcus** [comment]
> EDIT: and is there anywhere else, outside of formatting, that variables need to be accessed, beyond the ones I note above?

Outside of the formatting, it is used elsewhere to access key, doi, url.

**Comment by aikrahguzar** [comment]
> That makes sense in general.
> 
> But how would it interact with `bibtex-actions-get-value`? I'm particularly thinking of crucial fields like `=key=`/`id`.

We can change `bibtex-actions-get-value` to accept a list of fields so the functions can pass the list explicitly if the need more than one element.

With key there is another option, it is the hash key so we can always add ("=key=" . hashkey) to the candidate or better store the candidate data as `(key . candidate)` which would simplify the lookups by the key.

**Comment by bdarcus** [comment]
> ... or better store the candidate data as `(key . candidate)` which would simplify the lookups by the key.

Not sure that works with `completing-read`. AFAIK, it treats the car as the candidate string.

**Comment by aikrahguzar** [comment]
> Not sure that works with `completing-read`. AFAIK, it treats the car as the candidate string.

I was suggesting `(disaply-string key . candidate)`. Looking up a candidate by key is still easy,
```elisp
(defun lookup-candidate-by-key (key candidates)
         "Find CANDIDATE with key KEY"
         (cddr (seq-find (lambda (cand) (equal key (cadr cand))) candidates)))

**Comment by bdarcus** [comment]
> I was suggesting `(disaply-string key . candidate)` ...

Feel free to experiment, but then wouldn't you end up only searching/completing on the key?

**Comment by aikrahguzar** [comment]
> > I was suggesting `(disaply-string key . candidate)` ...
> 
> Feel free to experiment, but then wouldn't you end up only searching/completing on the key?

No? The display string is the same as before. It is the `car`, `cadr` is the key so we don't have to go through the whole candidate to find the key, then `cddr` is the candidate itself.

**Comment by bdarcus** [comment]
Right. I always get confused by the syntax with alists.

**Comment by bdarcus** [comment]
PS - make sure to use checkdoc ;-)
